 language: R
 cache: packages
 warnings_are_errors: true
 sudo: required
 r_build_args: --resave-data --no-manual 
 addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_packages: 
  - covr

after_success:
  - Rscript -e 'library(covr); codecov(token = "613d7607-72fb-44dd-87e7-1a13551ccb3c")'
