 language: r
 cache: packages
 r_build_args: --resave-data --no-manual --no-build-vignettes
 warnings_are_errors: false
 os: linux
 dist: xenial
 
 addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

 r_packages: 
    - covr

 after_success:
    - Rscript -e 'covr::codecov()'

