 language: R
 cache: packages
 warnings_are_errors: false
 sudo: required
 r_build_args: --resave-data 
 r_check_args: --resave-data 
 addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      - texinfo

r_packages: 
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
