 language: R
 cache: packages
 warnings_are_errors: false
 sudo: required
 r_build_args: --resave-data --no-manual 
 addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev

r_packages: 
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'
