 language: R
 cache: packages
 warnings_are_errors: false
 sudo: required
 addons:
  apt:
    packages:
      - libgdal-dev
      - libproj-dev
      
 after_success:
      - R -e 'covr::codecov()'
      - R -e 'covr::coveralls()'
